[package]
name = "logic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bincode = "=2.0.0-rc.3"
cxx = "1.0"
once_cell = "1.18.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[build-dependencies]

cxx-build = "1.0"
